# Generated by Django 6.0.6 on 2026-07-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
